-- heartbeat-beacon schema. Apply once as the database owner, then re-apply on
-- change (fully idempotent: CREATE ... IF NOT EXISTS, CREATE OR REPLACE):
--   psql "$OWNER_DSN" -f schema.sql -f grants.sql
-- Grants live in the companion grants.sql; roles are created once by a
-- superuser from roles.sql.
--
-- Two schemas: presence (the poller's beats) and signal (device-pushed
-- activity events). The proxy reads only the label-free views, so device
-- identities never enter the public-facing process.

CREATE SCHEMA IF NOT EXISTS presence;

CREATE TABLE IF NOT EXISTS presence.devices (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hostname TEXT NOT NULL UNIQUE,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- self-registration: the poller upserts every device it sees; only
    -- tracked ones get beats
    tracked BOOLEAN NOT NULL DEFAULT false,
    last_seen TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS presence.beats (
    device BIGINT NOT NULL REFERENCES presence.devices (id) ON DELETE CASCADE,
    beat_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (device, beat_at)
);

CREATE INDEX IF NOT EXISTS idx_beats_beat_at ON presence.beats (beat_at);

-- `presence.stats`: the proxy's whole presence snapshot behind one label-free
-- view. The proxy role reads this view only (grants.sql withholds the base
-- tables), so even a buggy future query cannot select a hostname or device id.
CREATE OR REPLACE VIEW presence.stats AS
WITH gaps AS (
    SELECT beat_at - lag(beat_at) OVER (ORDER BY beat_at) AS gap
    FROM presence.beats
)
SELECT
    (SELECT extract(epoch FROM max(beat_at))::bigint FROM presence.beats) AS last_seen,
    (SELECT count(*)::bigint FROM presence.beats) AS total_beats,
    (SELECT count(*)::bigint FROM presence.devices WHERE tracked) AS device_count,
    coalesce(extract(epoch FROM max(gap))::bigint, 0) AS longest_absence
FROM gaps;

CREATE SCHEMA IF NOT EXISTS signal;

CREATE TABLE IF NOT EXISTS signal.tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- sha256 hex digest of the per-device client token; the token itself
    -- exists on the device and nowhere else
    token_sha256 TEXT NOT NULL UNIQUE,
    -- attribution label, e.g. 'phone' or 'laptop-windows'
    device TEXT NOT NULL,
    -- sources this token may report, e.g. {phone-lock,editor-sync}
    sources TEXT[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- revocation is a timestamp, not a DELETE, so history keeps its attribution
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS signal.events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token BIGINT NOT NULL REFERENCES signal.tokens (id),
    source TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('start', 'stop', 'pulse')),
    at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signal_events_at ON signal.events (at);

-- `signal.source_state`: the latest event per (token, source), stripped of
-- every label. The proxy may read THIS view only: the session shape is
-- computed inside the database, so device/source identities never enter the
-- public-facing process.
CREATE OR REPLACE VIEW signal.source_state AS
SELECT DISTINCT ON (token, source) kind, at
FROM signal.events
ORDER BY token, source, at DESC, id DESC;

-- `signal.strong_stats`: bare count and latest timestamp of strong signals
-- (start/pulse). Label-free like source_state.
CREATE OR REPLACE VIEW signal.strong_stats AS
SELECT
    count(*)::bigint AS strong_total,
    extract(epoch FROM max(at))::bigint AS strong_last
FROM signal.events
WHERE kind IN ('start', 'pulse');

-- ---------------------------------------------------------------- substance
-- The substance logger's catalogue. Two reference tables and no log table:
-- what someone takes is theirs, so the beacon ships the *shape* of a catalogue
-- plus a neutral example seed (seed_substances.sql) and nothing else. Add your
-- own log table if you want one; the kinetics model reads the catalogue alone.
CREATE SCHEMA IF NOT EXISTS substance;

-- One substance and the absorption model that draws its curve. `model_family`
-- selects the functional form and `params` carries that family's parameters,
-- rather than fixed columns, because the families do not share a parameter set:
-- a depot ester has no dose split and an extended-release tablet has no serum
-- calibration. `unit_per_mg` lets a substance be logged in its natural unit
-- (µg for B12, g for alcohol) while the model works in mg throughout.
CREATE TABLE IF NOT EXISTS substance.catalog (
    name TEXT PRIMARY KEY,
    model_family TEXT NOT NULL,
    params JSONB NOT NULL DEFAULT '{}'::jsonb,
    label TEXT,
    color TEXT,
    category TEXT,
    unit TEXT NOT NULL DEFAULT 'mg',
    unit_per_mg DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (unit_per_mg > 0)
);

-- A named intake preset: "espresso" -> caffeine 80 mg. ON DELETE RESTRICT
-- rather than CASCADE, so removing a substance cannot silently take a set of
-- presets with it.
CREATE TABLE IF NOT EXISTS substance.templates (
    name TEXT PRIMARY KEY,
    substance TEXT NOT NULL REFERENCES substance.catalog (name) ON DELETE RESTRICT,
    dose_mg DOUBLE PRECISION NOT NULL CHECK (dose_mg > 0),
    label TEXT
);
